name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - java-kotlin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  build:
    name: Build with Gradle and Testcontainers
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Enable Docker (Testcontainers needs this)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo usermod -aG docker $USER
          sudo systemctl start docker

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build & Run Tests with Gradle
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          DOCKER_HOST: unix:///var/run/docker.sock
        run: ./gradlew clean test --info
